services:
  db:
    image: postgres:16
    container_name: sql_study_postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: antipat
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./sql_files:/sql_files

    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=pass psql -U user -d postgres -c \"SELECT 1 FROM pg_database WHERE datname = 'ec1';\" | grep -q 1"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - SQLstudy_fakerApp_network

  faker-app:
    build:
      context: ./pyapp
    container_name: sql_study_fakerApp
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pyapp:/app
    working_dir: /app
    command: sh -c "chmod +x /app/wait_db.sh && /app/wait_db.sh"
    networks:
      - SQLstudy_fakerApp_network

networks:
  SQLstudy_fakerApp_network:
    driver: bridge
